# Generated by Django 5.0.4 on 2024-04-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
