# Generated by Django 5.0.4 on 2024-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmv',
            name='rating',
        ),
        migrations.AddField(
            model_name='commentmv',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
