# Generated by Django 5.0.4 on 2024-04-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True)),
                ('movie_length', models.IntegerField()),
                ('date_of_release', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=300)),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True)),
                ('release_year', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=300)),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
    ]
