# Generated by Django 5.0.4 on 2024-04-10 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_movie_actor_movie_director_series_actor_and_more'),
        ('show_worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='show_worker.director'),
        ),
        migrations.AlterField(
            model_name='series',
            name='director_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='show_worker.director'),
        ),
    ]
