# Generated by Django 5.0.4 on 2024-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_alter_movie_director_alter_series_director_id'),
        ('show_worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='director_id',
            new_name='director',
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='movies', to='show_worker.actor'),
        ),
        migrations.AlterField(
            model_name='series',
            name='actor',
            field=models.ManyToManyField(related_name='series', to='show_worker.actor'),
        ),
    ]
