# Generated by Django 5.0.4 on 2024-04-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_rename_director_id_series_director_alter_movie_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='series',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='series',
            name='release_year',
        ),
        migrations.AddField(
            model_name='series',
            name='date_of_release',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_of_release',
            field=models.DateField(null=True),
        ),
    ]
