# Generated by Django 5.0.4 on 2024-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_remove_movie_is_new_remove_series_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='series',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
