# Generated by Django 5.0.4 on 2024-04-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_movie_is_new_series_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='show.genre'),
        ),
    ]
