# Generated by Django 5.0.4 on 2024-04-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_genre_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(related_name='series', to='show.genre'),
        ),
    ]
