# Generated by Django 5.0.4 on 2024-04-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_series_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='photo_url',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='series',
            name='photo_url',
            field=models.ImageField(upload_to='images'),
        ),
    ]
